#version 430 core

// In
layout (local_size_x = 10, local_size_y = 1, local_size_z = 1) in;

// Uniform
layout(rgba32f, binding = 0) uniform image2D render_texture;
uniform uint width;
uniform uint height;

void main() {
    float x = gl_GlobalInvocationID.x;
    for (int y = 0; y < height; y++) {
        vec3 color = vec3(ivec2(x, y).yxy) / width;
        imageStore(render_texture, ivec2(x, y), vec4(color, 1.0));
    }
}
